<a href="https://colab.research.google.com/github/nayoonchoi00/algo2024_PBL_indi/blob/main/PBL_Indiv_mode_median.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PBL(1): Individual Project Work

In [ ]:
project = "housingprice"
username = "22011271@sju.ac.kr"
password = "0128"

리더보드 제출을 위한 기본 설정: 아래 코드를 실행해주세요.

In [ ]:
import os
import urllib.request

if not os.path.exists("competition.py"):
    url = "https://raw.githubusercontent.com/agtechresearch/LectureAlgorithm/main/competition/competition.py"
    filename = "competition.py"
    urllib.request.urlretrieve(url, filename)

In [ ]:
import competition

# 파일 다운로드
competition.download_competition_files(project)

100%|██████████| 141k/141k [00:00<00:00, 3.32MiB/s]

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# 경고 무시
warnings.filterwarnings("ignore")

# Data 경로 설정
DATA_DIR = "data"

In [ ]:
# 학습에 사용할 과거 주택매매 data set 로드 (dataset.csv)
dataset = pd.read_csv(os.path.join(DATA_DIR, "dataset.csv"))

# problem set 로드 (problem.csv)
problemset = pd.read_csv(os.path.join(DATA_DIR, "problem.csv"))

In [ ]:
# 변수가 24개가 있으므로, 모든 변수를 출력하려면 다음과 같이 설정해야 함
pd.options.display.max_columns = 30

dataset  # 학습에 사용할 과거 주택매매 데이터셋 확인: 1340건의 과거 주택매매 데이터셋

,Id,LotArea,Street,LotConfig,OverallQual,OverallCond,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageType,GarageYrBlt,GarageCars,GarageArea,YrSold,SalePrice
0,1,8450,Pave,Inside,7,5,2003,2003,856,856,854,1710,2,1,3,1,8,0,Attchd,2003.0,2,548,2008,208500
1,2,9600,Pave,FR2,6,8,1976,1976,1262,1262,0,1262,2,0,3,1,6,1,Attchd,1976.0,2,460,2007,181500
2,3,11250,Pave,Inside,7,5,2001,2002,920,920,866,1786,2,1,3,1,6,1,Attchd,2001.0,2,608,2008,223500
3,4,9550,Pave,Corner,7,5,1915,1970,756,961,756,1717,1,0,3,1,7,1,Detchd,1998.0,3,642,2006,140000
4,5,14260,Pave,FR2,8,5,2000,2000,1145,1145,1053,2198,2,1,4,1,9,1,Attchd,2000.0,3,836,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,1336,9042,Pave,Inside,7,9,1941,2006,1152,1188,1152,2340,2,0,4,1,9,2,Attchd,1941.0,1,252,2010,266500
1336,1337,9717,Pave,Inside,5,6,1950,1996,1078,1078,0,1078,1,0,2,1,5,0,Attchd,1950.0,1,240,2010,142125
1337,1338,9937,Pave,Inside,5,6,1965,1965,1256,1256,0,1256,1,1,3,1,6,0,Attchd,1965.0,1,276,2008,147500
1338,1339,9600,Pave,Inside,5,7,1940,1950,728,976,332,1308,1,1,2,1,7,2,Detchd,1940.0,1,256,2009,160000
1339,1340,7390,Pave,Inside,5,7,1955,1955,1098,1098,0,1098,1,0,3,1,6,0,Attchd,1955.0,1,260,2008,135000

In [ ]:
# problem set 확인: 130건의 문제 데이터셋 (SalePrice를 예측해야 함)
problemset

,Id,LotArea,Street,LotConfig,OverallQual,OverallCond,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageType,GarageYrBlt,GarageCars,GarageArea,YrSold
0,1341,11200,Pave,Inside,5,5,1965,1965,1040,1040,0,1040,1,0,3,1,5,0,Detchd,1965,1,384,2008
1,1342,7200,Pave,Corner,5,7,1951,2000,900,900,0,900,1,0,3,1,5,0,Detchd,2005,2,576,2010
2,1343,16905,Pave,Inside,5,6,1959,1959,1350,1328,0,1328,1,1,2,1,5,2,Attchd,1959,1,308,2007
3,1344,9180,Pave,CulDSac,5,7,1983,1983,840,884,0,884,1,0,2,1,5,0,Attchd,1983,2,504,2007
4,1345,7200,Pave,Inside,5,7,1920,1996,530,581,530,1111,1,0,3,1,6,0,Detchd,1935,1,288,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,1466,11478,Pave,Inside,8,5,2007,2008,1704,1704,0,1704,2,0,3,1,7,1,Attchd,2008,3,772,2010
126,1467,16321,Pave,CulDSac,5,6,1957,1997,1484,1600,0,1600,1,0,2,1,6,2,Attchd,1957,1,319,2006
127,1468,6324,Pave,Inside,4,6,1927,1950,520,520,0,520,1,0,1,1,4,0,Detchd,1920,1,240,2008
128,1469,8500,Pave,Inside,4,4,1920,1950,649,649,668,1317,1,0,3,1,6,0,Detchd,1920,1,250,2008
129,1470,8544,Pave,CulDSac,5,6,1966,2006,1228,1228,0,1228,1,1,3,1,6,0,Attchd,1966,1,271,2008

In [ ]:
dataset.isnull().sum()

Id               0
LotArea          0
Street           0
LotConfig        0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
GrLivArea        0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageType      81
GarageYrBlt     81
GarageCars       0
GarageArea       0
YrSold           0
SalePrice        0
dtype: int64

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1340 non-null   int64
 1   LotArea       1340 non-null   int64
 2   Street        1340 non-null   object
 3   LotConfig     1340 non-null   object
 4   OverallQual   1340 non-null   int64
 5   OverallCond   1340 non-null   int64
 6   YearBuilt     1340 non-null   int64
 7   YearRemodAdd  1340 non-null   int64
 8   TotalBsmtSF   1340 non-null   int64
 9   1stFlrSF      1340 non-null   int64
 10  2ndFlrSF      1340 non-null   int64
 11  GrLivArea     1340 non-null   int64
 12  FullBath      1340 non-null   int64
 13  HalfBath      1340 non-null   int64
 14  BedroomAbvGr  1340 non-null   int64
 15  KitchenAbvGr  1340 non-null   int64
 16  TotRmsAbvGrd  1340 non-null   int64
 17  Fireplaces    1340 non-null   int64
 18  GarageType    1259 non-null   object
 19  GarageYrBlt   1259 non-null   float64
 20  GarageCars    1340 non-null   int64
 21  GarageArea    1340 non-null   int64
 22  YrSold        1340 non-null   int64
 23  SalePrice     1340 non-null   int64
dtypes: float64(1), int64(20), object(3)
memory usage: 251.4+ KB

In [ ]:
problemset.isnull().sum()

Id              0
LotArea         0
Street          0
LotConfig       0
OverallQual     0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
TotalBsmtSF     0
1stFlrSF        0
2ndFlrSF        0
GrLivArea       0
FullBath        0
HalfBath        0
BedroomAbvGr    0
KitchenAbvGr    0
TotRmsAbvGrd    0
Fireplaces      0
GarageType      0
GarageYrBlt     0
GarageCars      0
GarageArea      0
YrSold          0
dtype: int64

In [ ]:
problemset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            130 non-null    int64
 1   LotArea       130 non-null    int64
 2   Street        130 non-null    object
 3   LotConfig     130 non-null    object
 4   OverallQual   130 non-null    int64
 5   OverallCond   130 non-null    int64
 6   YearBuilt     130 non-null    int64
 7   YearRemodAdd  130 non-null    int64
 8   TotalBsmtSF   130 non-null    int64
 9   1stFlrSF      130 non-null    int64
 10  2ndFlrSF      130 non-null    int64
 11  GrLivArea     130 non-null    int64
 12  FullBath      130 non-null    int64
 13  HalfBath      130 non-null    int64
 14  BedroomAbvGr  130 non-null    int64
 15  KitchenAbvGr  130 non-null    int64
 16  TotRmsAbvGrd  130 non-null    int64
 17  Fireplaces    130 non-null    int64
 18  GarageType    130 non-null    object
 19  GarageYrBlt   130 non-null    int64
 20  GarageCars    130 non-null    int64
 21  GarageArea    130 non-null    int64
 22  YrSold        130 non-null    int64
dtypes: int64(20), object(3)
memory usage: 23.5+ KB

In [ ]:
print(dataset['Street'].unique())
print(problemset['Street'].unique())

['Pave' 'Grvl']
['Pave' 'Grvl']

In [ ]:
print(dataset['LotConfig'].unique())
print(problemset['LotConfig'].unique())

['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3']
['Inside' 'Corner' 'CulDSac' 'FR3' 'FR2']

In [ ]:
print(dataset['GarageType'].unique())
print(problemset['GarageType'].unique())

['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']
['Detchd' 'Attchd' 'BuiltIn' '2Types']

## 데이터 전처리 및 모델 학습

In [ ]:
import pandas as pd

# 주어진 데이터프레임에서 수치형 변수와 범주형 변수 구분
numeric_columns = dataset.select_dtypes(include=['int', 'float']).columns
categorical_columns = dataset.select_dtypes(include=['object']).columns

# 수치형 변수의 결측치를 중앙값(median)으로 대체
for column in numeric_columns:
    median_value = dataset[column].median()
    dataset[column].fillna(median_value, inplace=True)

# 범주형 변수의 결측치를 최빈값(mode)으로 대체
for column in categorical_columns:
    mode_value = dataset[column].mode()[0]  # 최빈값이 여러 개일 경우 첫 번째 값을 선택
    dataset[column].fillna(mode_value, inplace=True)

In [ ]:
dataset.isnull().sum()

Id              0
LotArea         0
Street          0
LotConfig       0
OverallQual     0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
TotalBsmtSF     0
1stFlrSF        0
2ndFlrSF        0
GrLivArea       0
FullBath        0
HalfBath        0
BedroomAbvGr    0
KitchenAbvGr    0
TotRmsAbvGrd    0
Fireplaces      0
GarageType      0
GarageYrBlt     0
GarageCars      0
GarageArea      0
YrSold          0
SalePrice       0
dtype: int64

In [ ]:
# data 와 problem 데이터들을 합쳐서 하나의 데이터로 만들어줍니다 --> 아래의 데이터 전처리 후 다시 분리할 예정
all_data = pd.concat([dataset, problemset], ignore_index=True)

# Id 열을 제거
all_data = all_data.drop(["Id"], axis=1)

In [ ]:
# 학습 데이터와 문제 데이터로 다시금 분리
train_data = all_data[: len(dataset)]
problem_data = all_data[len(dataset):]

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LotArea       1340 non-null   int64
 1   Street        1340 non-null   object
 2   LotConfig     1340 non-null   object
 3   OverallQual   1340 non-null   int64
 4   OverallCond   1340 non-null   int64
 5   YearBuilt     1340 non-null   int64
 6   YearRemodAdd  1340 non-null   int64
 7   TotalBsmtSF   1340 non-null   int64
 8   1stFlrSF      1340 non-null   int64
 9   2ndFlrSF      1340 non-null   int64
 10  GrLivArea     1340 non-null   int64
 11  FullBath      1340 non-null   int64
 12  HalfBath      1340 non-null   int64
 13  BedroomAbvGr  1340 non-null   int64
 14  KitchenAbvGr  1340 non-null   int64
 15  TotRmsAbvGrd  1340 non-null   int64
 16  Fireplaces    1340 non-null   int64
 17  GarageType    1340 non-null   object
 18  GarageYrBlt   1340 non-null   float64
 19  GarageCars    1340 non-null   int64
 20  GarageArea    1340 non-null   int64
 21  YrSold        1340 non-null   int64
 22  SalePrice     1340 non-null   float64
dtypes: float64(2), int64(18), object(3)
memory usage: 240.9+ KB

In [ ]:
problem_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 1340 to 1469
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LotArea       130 non-null    int64
 1   Street        130 non-null    object
 2   LotConfig     130 non-null    object
 3   OverallQual   130 non-null    int64
 4   OverallCond   130 non-null    int64
 5   YearBuilt     130 non-null    int64
 6   YearRemodAdd  130 non-null    int64
 7   TotalBsmtSF   130 non-null    int64
 8   1stFlrSF      130 non-null    int64
 9   2ndFlrSF      130 non-null    int64
 10  GrLivArea     130 non-null    int64
 11  FullBath      130 non-null    int64
 12  HalfBath      130 non-null    int64
 13  BedroomAbvGr  130 non-null    int64
 14  KitchenAbvGr  130 non-null    int64
 15  TotRmsAbvGrd  130 non-null    int64
 16  Fireplaces    130 non-null    int64
 17  GarageType    130 non-null    object
 18  GarageYrBlt   130 non-null    float64
 19  GarageCars    130 non-null    int64
 20  GarageArea    130 non-null    int64
 21  YrSold        130 non-null    int64
 22  SalePrice     0 non-null      float64
dtypes: float64(2), int64(18), object(3)
memory usage: 23.5+ KB

더미변수 변환(원핫인코딩)

In [ ]:
# train_data 더미변수 변환

import pandas as pd

# 첫 번째 object type 열 선택
categorical_column1 = 'Street'
dummies1 = pd.get_dummies(train_data[categorical_column1], prefix=categorical_column1)

# 두 번째 object type 열 선택
categorical_column2 = 'LotConfig'
dummies2 = pd.get_dummies(train_data[categorical_column2], prefix=categorical_column2)

# 세 번째 object type 열 선택
categorical_column3 = 'GarageType'
dummies3 = pd.get_dummies(train_data[categorical_column3], prefix=categorical_column3)

# 기존 데이터프레임과 더미 변수를 합치기
train_data = pd.concat([train_data, dummies1, dummies2, dummies3], axis=1)

# 더미 변수의 True/False를 1/0으로 변환
train_data.replace({True: 1, False: 0}, inplace=True)

# 원래 열 삭제
train_data.drop([categorical_column1, categorical_column2, categorical_column3], axis=1, inplace=True)

# 결과 확인
train_data.head()

,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,...,YrSold,SalePrice,Street_Grvl,Street_Pave,LotConfig_Corner,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,GarageType_2Types,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd
0,8450,7,5,2003,2003,856,856,854,1710,2,1,3,1,8,0,...,2008,208500.0,0,1,0,0,0,0,1,0,1,0,0,0,0
1,9600,6,8,1976,1976,1262,1262,0,1262,2,0,3,1,6,1,...,2007,181500.0,0,1,0,0,1,0,0,0,1,0,0,0,0
2,11250,7,5,2001,2002,920,920,866,1786,2,1,3,1,6,1,...,2008,223500.0,0,1,0,0,0,0,1,0,1,0,0,0,0
3,9550,7,5,1915,1970,756,961,756,1717,1,0,3,1,7,1,...,2006,140000.0,0,1,1,0,0,0,0,0,0,0,0,0,1
4,14260,8,5,2000,2000,1145,1145,1053,2198,2,1,4,1,9,1,...,2008,250000.0,0,1,0,0,1,0,0,0,1,0,0,0,0

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   LotArea             1340 non-null   int64
 1   OverallQual         1340 non-null   int64
 2   OverallCond         1340 non-null   int64
 3   YearBuilt           1340 non-null   int64
 4   YearRemodAdd        1340 non-null   int64
 5   TotalBsmtSF         1340 non-null   int64
 6   1stFlrSF            1340 non-null   int64
 7   2ndFlrSF            1340 non-null   int64
 8   GrLivArea           1340 non-null   int64
 9   FullBath            1340 non-null   int64
 10  HalfBath            1340 non-null   int64
 11  BedroomAbvGr        1340 non-null   int64
 12  KitchenAbvGr        1340 non-null   int64
 13  TotRmsAbvGrd        1340 non-null   int64
 14  Fireplaces          1340 non-null   int64
 15  GarageYrBlt         1340 non-null   float64
 16  GarageCars          1340 non-null   int64
 17  GarageArea          1340 non-null   int64
 18  YrSold              1340 non-null   int64
 19  SalePrice           1340 non-null   float64
 20  Street_Grvl         1340 non-null   int64
 21  Street_Pave         1340 non-null   int64
 22  LotConfig_Corner    1340 non-null   int64
 23  LotConfig_CulDSac   1340 non-null   int64
 24  LotConfig_FR2       1340 non-null   int64
 25  LotConfig_FR3       1340 non-null   int64
 26  LotConfig_Inside    1340 non-null   int64
 27  GarageType_2Types   1340 non-null   int64
 28  GarageType_Attchd   1340 non-null   int64
 29  GarageType_Basment  1340 non-null   int64
 30  GarageType_BuiltIn  1340 non-null   int64
 31  GarageType_CarPort  1340 non-null   int64
 32  GarageType_Detchd   1340 non-null   int64
dtypes: float64(2), int64(31)
memory usage: 345.6 KB

In [ ]:
# problem_data 더미변수 변환

import pandas as pd

# 첫 번째 object type 열 선택
categorical_column1 = 'Street'
dummies1 = pd.get_dummies(problem_data[categorical_column1], prefix=categorical_column1)

# 두 번째 object type 열 선택
categorical_column2 = 'LotConfig'
dummies2 = pd.get_dummies(problem_data[categorical_column2], prefix=categorical_column2)

# 세 번째 object type 열 선택
categorical_column3 = 'GarageType'
dummies3 = pd.get_dummies(problem_data[categorical_column3], prefix=categorical_column3)

# 기존 데이터프레임과 더미 변수를 합치기
problem_data = pd.concat([problem_data, dummies1, dummies2, dummies3], axis=1)

# 더미 변수의 True/False를 1/0으로 변환
problem_data.replace({True: 1, False: 0}, inplace=True)

# 원래 열 삭제
problem_data.drop([categorical_column1, categorical_column2, categorical_column3], axis=1, inplace=True)

# 결과 확인
problem_data.head()

,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,...,GarageCars,GarageArea,YrSold,SalePrice,Street_Grvl,Street_Pave,LotConfig_Corner,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,GarageType_2Types,GarageType_Attchd,GarageType_BuiltIn,GarageType_Detchd
1340,11200,5,5,1965,1965,1040,1040,0,1040,1,0,3,1,5,0,...,1,384,2008,NaN,0,1,0,0,0,0,1,0,0,0,1
1341,7200,5,7,1951,2000,900,900,0,900,1,0,3,1,5,0,...,2,576,2010,NaN,0,1,1,0,0,0,0,0,0,0,1
1342,16905,5,6,1959,1959,1350,1328,0,1328,1,1,2,1,5,2,...,1,308,2007,NaN,0,1,0,0,0,0,1,0,1,0,0
1343,9180,5,7,1983,1983,840,884,0,884,1,0,2,1,5,0,...,2,504,2007,NaN,0,1,0,1,0,0,0,0,1,0,0
1344,7200,5,7,1920,1996,530,581,530,1111,1,0,3,1,6,0,...,1,288,2007,NaN,0,1,0,0,0,0,1,0,0,0,1

In [ ]:
problem_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 1340 to 1469
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   LotArea             130 non-null    int64
 1   OverallQual         130 non-null    int64
 2   OverallCond         130 non-null    int64
 3   YearBuilt           130 non-null    int64
 4   YearRemodAdd        130 non-null    int64
 5   TotalBsmtSF         130 non-null    int64
 6   1stFlrSF            130 non-null    int64
 7   2ndFlrSF            130 non-null    int64
 8   GrLivArea           130 non-null    int64
 9   FullBath            130 non-null    int64
 10  HalfBath            130 non-null    int64
 11  BedroomAbvGr        130 non-null    int64
 12  KitchenAbvGr        130 non-null    int64
 13  TotRmsAbvGrd        130 non-null    int64
 14  Fireplaces          130 non-null    int64
 15  GarageYrBlt         130 non-null    float64
 16  GarageCars          130 non-null    int64
 17  GarageArea          130 non-null    int64
 18  YrSold              130 non-null    int64
 19  SalePrice           0 non-null      float64
 20  Street_Grvl         130 non-null    int64
 21  Street_Pave         130 non-null    int64
 22  LotConfig_Corner    130 non-null    int64
 23  LotConfig_CulDSac   130 non-null    int64
 24  LotConfig_FR2       130 non-null    int64
 25  LotConfig_FR3       130 non-null    int64
 26  LotConfig_Inside    130 non-null    int64
 27  GarageType_2Types   130 non-null    int64
 28  GarageType_Attchd   130 non-null    int64
 29  GarageType_BuiltIn  130 non-null    int64
 30  GarageType_Detchd   130 non-null    int64
dtypes: float64(2), int64(29)
memory usage: 31.6 KB

In [ ]:
problem_data.insert(29,'GarageType_Basment', 0, allow_duplicates=False)

problem_data.insert(31, 'GarageType_CarPort', 0, allow_duplicates=False)

In [ ]:
problem_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 1340 to 1469
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   LotArea             130 non-null    int64
 1   OverallQual         130 non-null    int64
 2   OverallCond         130 non-null    int64
 3   YearBuilt           130 non-null    int64
 4   YearRemodAdd        130 non-null    int64
 5   TotalBsmtSF         130 non-null    int64
 6   1stFlrSF            130 non-null    int64
 7   2ndFlrSF            130 non-null    int64
 8   GrLivArea           130 non-null    int64
 9   FullBath            130 non-null    int64
 10  HalfBath            130 non-null    int64
 11  BedroomAbvGr        130 non-null    int64
 12  KitchenAbvGr        130 non-null    int64
 13  TotRmsAbvGrd        130 non-null    int64
 14  Fireplaces          130 non-null    int64
 15  GarageYrBlt         130 non-null    float64
 16  GarageCars          130 non-null    int64
 17  GarageArea          130 non-null    int64
 18  YrSold              130 non-null    int64
 19  SalePrice           0 non-null      float64
 20  Street_Grvl         130 non-null    int64
 21  Street_Pave         130 non-null    int64
 22  LotConfig_Corner    130 non-null    int64
 23  LotConfig_CulDSac   130 non-null    int64
 24  LotConfig_FR2       130 non-null    int64
 25  LotConfig_FR3       130 non-null    int64
 26  LotConfig_Inside    130 non-null    int64
 27  GarageType_2Types   130 non-null    int64
 28  GarageType_Attchd   130 non-null    int64
 29  GarageType_Basment  130 non-null    int64
 30  GarageType_BuiltIn  130 non-null    int64
 31  GarageType_CarPort  130 non-null    int64
 32  GarageType_Detchd   130 non-null    int64
dtypes: float64(2), int64(31)
memory usage: 33.6 KB

#**모델학습**

In [ ]:
# 학습 데이터의 SalePrice 열을 제외한 나머지 열을 X로 지정, SalePrice 열을 Y로 지정
X = train_data.drop("SalePrice", axis=1)
Y = train_data["SalePrice"]

In [ ]:
# 모델 학습을 위해 학습 데이터를 80%의 학습 데이터(train)와 20%의 검증 데이터(test)로 나눔
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

# **Gradient Boosting**

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

# 그래디언트 부스팅 모델 생성 및 학습
model = GradientBoostingRegressor(n_estimators=1000, learning_rate=0.1, max_depth=3, random_state=100)
model.fit(x_train, y_train)

# 검증 데이터에 대한 예측
y_pred = model.predict(x_test)

In [ ]:
# train 데이터와 test 데이터에 대한 예측값을 구하고 RMSE 값을 계산
from sklearn.metrics import mean_squared_error

train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

print("Train RMSE :", mean_squared_error(y_train, train_pred) ** 0.5)
print("Test RMSE :", mean_squared_error(y_test, test_pred) ** 0.5)

Train RMSE : 4050.8278757142807
Test RMSE : 27784.344804453158

#**Decision Tree**

In [ ]:
'''
# DecisionTree 모델을 사용하여 학습
from sklearn.tree import DecisionTreeClassifier

# 의사 결정 트리 모델 생성
model = DecisionTreeClassifier()

# 모델 학습
model.fit(x_train,y_train)
'''

In [ ]:
'''
# train 데이터와 test 데이터에 대한 예측값을 구하고 RMSE 값을 계산
from sklearn.metrics import mean_squared_error

train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

print("Train RMSE :", mean_squared_error(y_train, train_pred) ** 0.5)
print("Test RMSE :", mean_squared_error(y_test, test_pred) ** 0.5)
'''

# **Polynomial Regression**

In [ ]:
'''
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# 다항식 특성 추가
degree = 2  # 다항식 차수 (하이퍼파라미터)
poly_features = PolynomialFeatures(degree=degree)
X_poly = poly_features.fit_transform(X)

# 선형 회귀 모델 생성 및 학습
model = LinearRegression()  # 모델 초기화
model.fit(x_train, y_train)  # 모델 학습

# 테스트 데이터에 대한 예측
y_pred = model.predict(x_test)
'''

In [ ]:
'''
# train 데이터와 test 데이터에 대한 예측값을 구하고 RMSE 값을 계산
from sklearn.metrics import mean_squared_error

train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

print("Train RMSE :", mean_squared_error(y_train, train_pred) ** 0.5)
print("Test RMSE :", mean_squared_error(y_test, test_pred) ** 0.5)
'''

# **XGBoost**

In [ ]:
'''
# XGBoost 모델을 사용하여 학습
from xgboost.sklearn import XGBRegressor

# XGBoost 모델 생성
model = XGBRegressor()

# 모델 학습
model.fit(x_train,y_train)
'''

In [ ]:
'''
# train 데이터와 test 데이터에 대한 예측값을 구하고 RMSE 값을 계산
from sklearn.metrics import mean_squared_error

train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

print("Train RMSE :", mean_squared_error(y_train, train_pred) ** 0.5)
print("Test RMSE :", mean_squared_error(y_test, test_pred) ** 0.5)
'''

## Problem set 문제에 대한 집값예측 및 리더보드 결과 제출

- 아래 제출 프로세스가 느리다고 중지 후 다시 코드를 여러차례 재실행하는 경우 패널티가 발생할 수 있습니다. (제출 과정에서 제출 횟수 이슈 발생 가능: 하루 최대 200회 까지 가능)
- 제출에 성공할 경우, "제출에 성공하였습니다"의 메세지와 함께 제출 결과 RMSE 가 화면에 출력됩니다.
- 제출결과는 또한 [대회 페이지(리더보드 서버)](https://agtechresearch.pythonanywhere.com/competitions/housingprice/)의 `리더보드` 와 `제출` 탭에서 확인할 수 있습니다.

In [ ]:
# 전처리 과정 중에 SalePrice 가 0으로 채워져 있기 때문에, problem_data 에서 SalePrice를 다시 제거
problem_data = problem_data.drop("SalePrice", axis=1)
# 문제 데이터(problem data)에 대한 예측값을 구함
problem_pred = model.predict(problem_data)

In [ ]:
# 리더보드 서버 제출을 위한 파일 생성
submission = pd.read_csv(os.path.join(DATA_DIR, "submission.csv"))
submission["SalePrice"] = problem_pred

# 예측 결과 화면에 출력 후 제출
display(submission)
competition.submit(project, username, password, submission)

       Id      SalePrice
0    1341  129445.136262
1    1342  124093.718069
2    1343  159269.170830
3    1344  131772.170100
4    1345  101978.932458
..    ...            ...
125  1466  293547.551171
126  1467  182084.146401
127  1468   75785.869303
128  1469   91465.498962
129  1470  144743.418139

[130 rows x 2 columns]

아이디:  22011271@sju.ac.kr
파일명:  submissions/20240510-130212-submission.csv
============================================================
[제출에 성공하였습니다]
제출 결과: 28756.053498812045